[project]
name = "pseupira"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bio>=1.7.1",
    "htseq>=2.0.9",
    "numpy>=2.2.4",
    "polars>=1.25.2",
]
